//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Custom.proto
// Note: requires additional types generated from: PB.proto
namespace Com.Communication
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddGoodData")]
  public partial class AddGoodData : global::ProtoBuf.IExtensible
  {
    public AddGoodData() {}
    
    private string _goodId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"goodId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string goodId
    {
      get { return _goodId; }
      set { _goodId = value; }
    }
    private int _num = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddEquipData")]
  public partial class AddEquipData : global::ProtoBuf.IExtensible
  {
    public AddEquipData() {}
    
    private string _equipId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"equipId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string equipId
    {
      get { return _equipId; }
      set { _equipId = value; }
    }
    private int _num = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OneKeyEquipEquip")]
  public partial class OneKeyEquipEquip : global::ProtoBuf.IExtensible
  {
    public OneKeyEquipEquip() {}
    
    private long _sourceUid = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sourceUid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sourceUid
    {
      get { return _sourceUid; }
      set { _sourceUid = value; }
    }
    private long _targetUid = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"targetUid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long targetUid
    {
      get { return _targetUid; }
      set { _targetUid = value; }
    }
    private int _equipPos = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"equipPos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipPos
    {
      get { return _equipPos; }
      set { _equipPos = value; }
    }
    private bool _magic = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"magic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool magic
    {
      get { return _magic; }
      set { _magic = value; }
    }
    private long _targetHeroUid = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"targetHeroUid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long targetHeroUid
    {
      get { return _targetHeroUid; }
      set { _targetHeroUid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CustomInstplayer")]
  public partial class CustomInstplayer : global::ProtoBuf.IExtensible
  {
    public CustomInstplayer() {}
    
    private PBInstPlayer _instPlayer = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"instPlayer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBInstPlayer instPlayer
    {
      get { return _instPlayer; }
      set { _instPlayer = value; }
    }
    private long _coin = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private long _ruby = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ruby", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long ruby
    {
      get { return _ruby; }
      set { _ruby = value; }
    }
    private long _skill_point = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"skill_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long skill_point
    {
      get { return _skill_point; }
      set { _skill_point = value; }
    }
    private long _equip_val = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"equip_val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long equip_val
    {
      get { return _equip_val; }
      set { _equip_val = value; }
    }
    private long _exp = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private long _hero_val = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"hero_val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long hero_val
    {
      get { return _hero_val; }
      set { _hero_val = value; }
    }
    private long _girl_val = default(long);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"girl_val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long girl_val
    {
      get { return _girl_val; }
      set { _girl_val = value; }
    }
    private long _xiuwei_val = default(long);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"xiuwei_val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long xiuwei_val
    {
      get { return _xiuwei_val; }
      set { _xiuwei_val = value; }
    }
    private long _yueli_val = default(long);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"yueli_val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long yueli_val
    {
      get { return _yueli_val; }
      set { _yueli_val = value; }
    }
    private long _wencai_val = default(long);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"wencai_val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long wencai_val
    {
      get { return _wencai_val; }
      set { _wencai_val = value; }
    }
    private long _menpai_weiwang = default(long);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"menpai_weiwang", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long menpai_weiwang
    {
      get { return _menpai_weiwang; }
      set { _menpai_weiwang = value; }
    }
    private long _menpai_gongxian = default(long);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"menpai_gongxian", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long menpai_gongxian
    {
      get { return _menpai_gongxian; }
      set { _menpai_gongxian = value; }
    }
    private int _main_hero_level = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"main_hero_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int main_hero_level
    {
      get { return _main_hero_level; }
      set { _main_hero_level = value; }
    }
    private int _jingjie_level = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"jingjie_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int jingjie_level
    {
      get { return _jingjie_level; }
      set { _jingjie_level = value; }
    }
    private int _yueli_level = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"yueli_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int yueli_level
    {
      get { return _yueli_level; }
      set { _yueli_level = value; }
    }
    private int _hero_icon_id = default(int);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"hero_icon_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hero_icon_id
    {
      get { return _hero_icon_id; }
      set { _hero_icon_id = value; }
    }
    private PBInstHero _mainPlayerHero = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"mainPlayerHero", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBInstHero mainPlayerHero
    {
      get { return _mainPlayerHero; }
      set { _mainPlayerHero = value; }
    }
    private long _xiuzhenDays = default(long);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"xiuzhenDays", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long xiuzhenDays
    {
      get { return _xiuzhenDays; }
      set { _xiuzhenDays = value; }
    }
    private long _mingsheng_val = default(long);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"mingsheng_val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long mingsheng_val
    {
      get { return _mingsheng_val; }
      set { _mingsheng_val = value; }
    }
    private long _pvp_rank = default(long);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"pvp_rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long pvp_rank
    {
      get { return _pvp_rank; }
      set { _pvp_rank = value; }
    }
    private int _zb_id = default(int);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"zb_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int zb_id
    {
      get { return _zb_id; }
      set { _zb_id = value; }
    }
    private PBInstFriend _instFriend = null;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"instFriend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBInstFriend instFriend
    {
      get { return _instFriend; }
      set { _instFriend = value; }
    }
    private int _player_attribute = default(int);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"player_attribute", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int player_attribute
    {
      get { return _player_attribute; }
      set { _player_attribute = value; }
    }
    private int _player_image = default(int);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"player_image", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int player_image
    {
      get { return _player_image; }
      set { _player_image = value; }
    }
    private int _player_jiyuan = default(int);
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"player_jiyuan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int player_jiyuan
    {
      get { return _player_jiyuan; }
      set { _player_jiyuan = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CustomMenpaiInfo")]
  public partial class CustomMenpaiInfo : global::ProtoBuf.IExtensible
  {
    public CustomMenpaiInfo() {}
    
    private readonly global::System.Collections.Generic.List<CustomInstplayer> _instplayers = new global::System.Collections.Generic.List<CustomInstplayer>();
    [global::ProtoBuf.ProtoMember(1, Name=@"instplayers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CustomInstplayer> instplayers
    {
      get { return _instplayers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CustomPayItem")]
  public partial class CustomPayItem : global::ProtoBuf.IExtensible
  {
    public CustomPayItem() {}
    
    private string _uid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private float _amount = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _notifyurl = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"notifyurl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string notifyurl
    {
      get { return _notifyurl; }
      set { _notifyurl = value; }
    }
    private string _returnurl = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"returnurl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string returnurl
    {
      get { return _returnurl; }
      set { _returnurl = value; }
    }
    private string _ordernum = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"ordernum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ordernum
    {
      get { return _ordernum; }
      set { _ordernum = value; }
    }
    private string _orderuid = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"orderuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string orderuid
    {
      get { return _orderuid; }
      set { _orderuid = value; }
    }
    private string _goodname = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"goodname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string goodname
    {
      get { return _goodname; }
      set { _goodname = value; }
    }
    private string _key = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneInfo")]
  public partial class ZoneInfo : global::ProtoBuf.IExtensible
  {
    public ZoneInfo() {}
    
    private string _zoneId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"zoneId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string zoneId
    {
      get { return _zoneId; }
      set { _zoneId = value; }
    }
    private string _zoneName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"zoneName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string zoneName
    {
      get { return _zoneName; }
      set { _zoneName = value; }
    }
    private string _zoneState = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"zoneState", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string zoneState
    {
      get { return _zoneState; }
      set { _zoneState = value; }
    }
    private string _zoneIP = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"zoneIP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string zoneIP
    {
      get { return _zoneIP; }
      set { _zoneIP = value; }
    }
    private int _globalGUID = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"globalGUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int globalGUID
    {
      get { return _globalGUID; }
      set { _globalGUID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CustomFullInstPlayer")]
  public partial class CustomFullInstPlayer : global::ProtoBuf.IExtensible
  {
    public CustomFullInstPlayer() {}
    
    private PBInstPlayer _instPlayer = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"instPlayer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBInstPlayer instPlayer
    {
      get { return _instPlayer; }
      set { _instPlayer = value; }
    }
    private string _playerKey = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerKey
    {
      get { return _playerKey; }
      set { _playerKey = value; }
    }
    private readonly global::System.Collections.Generic.List<PBInstHero> _instHeros = new global::System.Collections.Generic.List<PBInstHero>();
    [global::ProtoBuf.ProtoMember(3, Name=@"instHeros", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBInstHero> instHeros
    {
      get { return _instHeros; }
    }
  
    private readonly global::System.Collections.Generic.List<PBInstEquip> _instEquips = new global::System.Collections.Generic.List<PBInstEquip>();
    [global::ProtoBuf.ProtoMember(4, Name=@"instEquips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBInstEquip> instEquips
    {
      get { return _instEquips; }
    }
  
    private readonly global::System.Collections.Generic.List<PBInstGood> _instGoods = new global::System.Collections.Generic.List<PBInstGood>();
    [global::ProtoBuf.ProtoMember(5, Name=@"instGoods", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBInstGood> instGoods
    {
      get { return _instGoods; }
    }
  
    private readonly global::System.Collections.Generic.List<PBInstSkill> _instSkills = new global::System.Collections.Generic.List<PBInstSkill>();
    [global::ProtoBuf.ProtoMember(6, Name=@"instSkills", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBInstSkill> instSkills
    {
      get { return _instSkills; }
    }
  
    private readonly global::System.Collections.Generic.List<PBInstTask> _instTasks = new global::System.Collections.Generic.List<PBInstTask>();
    [global::ProtoBuf.ProtoMember(7, Name=@"instTasks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBInstTask> instTasks
    {
      get { return _instTasks; }
    }
  
    private readonly global::System.Collections.Generic.List<PBInstPlayerProp> _instPlayerProps = new global::System.Collections.Generic.List<PBInstPlayerProp>();
    [global::ProtoBuf.ProtoMember(8, Name=@"instPlayerProps", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBInstPlayerProp> instPlayerProps
    {
      get { return _instPlayerProps; }
    }
  
    private readonly global::System.Collections.Generic.List<PBInstMail> _instMails = new global::System.Collections.Generic.List<PBInstMail>();
    [global::ProtoBuf.ProtoMember(9, Name=@"instMails", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBInstMail> instMails
    {
      get { return _instMails; }
    }
  
    private readonly global::System.Collections.Generic.List<PBInstCopy> _instCopys = new global::System.Collections.Generic.List<PBInstCopy>();
    [global::ProtoBuf.ProtoMember(10, Name=@"instCopys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBInstCopy> instCopys
    {
      get { return _instCopys; }
    }
  
    private readonly global::System.Collections.Generic.List<PBInstGirl> _instGirls = new global::System.Collections.Generic.List<PBInstGirl>();
    [global::ProtoBuf.ProtoMember(11, Name=@"instGirls", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBInstGirl> instGirls
    {
      get { return _instGirls; }
    }
  
    private readonly global::System.Collections.Generic.List<PBInstChapter> _instChapters = new global::System.Collections.Generic.List<PBInstChapter>();
    [global::ProtoBuf.ProtoMember(12, Name=@"instChapters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBInstChapter> instChapters
    {
      get { return _instChapters; }
    }
  
    private readonly global::System.Collections.Generic.List<PBInstPlayerShop> _instPlayerShops = new global::System.Collections.Generic.List<PBInstPlayerShop>();
    [global::ProtoBuf.ProtoMember(13, Name=@"instPlayerShops", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBInstPlayerShop> instPlayerShops
    {
      get { return _instPlayerShops; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatBaseInfo")]
  public partial class ChatBaseInfo : global::ProtoBuf.IExtensible
  {
    public ChatBaseInfo() {}
    
    private int _chatType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"chatType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chatType
    {
      get { return _chatType; }
      set { _chatType = value; }
    }
    private int _contentType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"contentType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int contentType
    {
      get { return _contentType; }
      set { _contentType = value; }
    }
    private string _chatTitle = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"chatTitle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string chatTitle
    {
      get { return _chatTitle; }
      set { _chatTitle = value; }
    }
    private string _chatContent = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"chatContent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string chatContent
    {
      get { return _chatContent; }
      set { _chatContent = value; }
    }
    private long _targetPid = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"targetPid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long targetPid
    {
      get { return _targetPid; }
      set { _targetPid = value; }
    }
    private string _targetNickName = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"targetNickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string targetNickName
    {
      get { return _targetNickName; }
      set { _targetNickName = value; }
    }
    private long _targetPLId = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"targetPLId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long targetPLId
    {
      get { return _targetPLId; }
      set { _targetPLId = value; }
    }
    private int _targetHPId = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"targetHPId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int targetHPId
    {
      get { return _targetHPId; }
      set { _targetHPId = value; }
    }
    private long _sendTime = default(long);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"sendTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sendTime
    {
      get { return _sendTime; }
      set { _sendTime = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _actionParams = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(10, Name=@"actionParams", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> actionParams
    {
      get { return _actionParams; }
    }
  
    private int _targetZoneid = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"targetZoneid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int targetZoneid
    {
      get { return _targetZoneid; }
      set { _targetZoneid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatListItem")]
  public partial class ChatListItem : global::ProtoBuf.IExtensible
  {
    public ChatListItem() {}
    
    private ChatBaseInfo _baseInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"baseInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ChatBaseInfo baseInfo
    {
      get { return _baseInfo; }
      set { _baseInfo = value; }
    }
    private long _sendPid = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sendPid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sendPid
    {
      get { return _sendPid; }
      set { _sendPid = value; }
    }
    private string _sendNickName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sendNickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sendNickName
    {
      get { return _sendNickName; }
      set { _sendNickName = value; }
    }
    private int _sendHPId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sendHPId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sendHPId
    {
      get { return _sendHPId; }
      set { _sendHPId = value; }
    }
    private long _sendPLId = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sendPLId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sendPLId
    {
      get { return _sendPLId; }
      set { _sendPLId = value; }
    }
    private long _sendTime = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"sendTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sendTime
    {
      get { return _sendTime; }
      set { _sendTime = value; }
    }
    private int _sendZoneid = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"sendZoneid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sendZoneid
    {
      get { return _sendZoneid; }
      set { _sendZoneid = value; }
    }
    private string _uid = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CustomMenpaiBossRankInfo")]
  public partial class CustomMenpaiBossRankInfo : global::ProtoBuf.IExtensible
  {
    public CustomMenpaiBossRankInfo() {}
    
    private CustomInstplayer _instplayers = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"instplayers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CustomInstplayer instplayers
    {
      get { return _instplayers; }
      set { _instplayers = value; }
    }
    private PBInstMenpaiBossDateRank _pbInstMenpaiBossDateRank = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pbInstMenpaiBossDateRank", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBInstMenpaiBossDateRank pbInstMenpaiBossDateRank
    {
      get { return _pbInstMenpaiBossDateRank; }
      set { _pbInstMenpaiBossDateRank = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CustomKuafuBossRankInfo")]
  public partial class CustomKuafuBossRankInfo : global::ProtoBuf.IExtensible
  {
    public CustomKuafuBossRankInfo() {}
    
    private CustomInstplayer _instplayers = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"instplayers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CustomInstplayer instplayers
    {
      get { return _instplayers; }
      set { _instplayers = value; }
    }
    private PBConfigKuafuBossDateRank _pbConfigKuafuBossDateRank = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pbConfigKuafuBossDateRank", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PBConfigKuafuBossDateRank pbConfigKuafuBossDateRank
    {
      get { return _pbConfigKuafuBossDateRank; }
      set { _pbConfigKuafuBossDateRank = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}